#!/bin/bash

# Read in the input file
input_file="$1"

# Extract the first letter of each line
acrostic=""
while read -r line; do
  first_letter=$(echo "$line" | cut -c 1)
  acrostic="$acrostic$first_letter"
done < "$input_file"

# Print the decoded message
echo -e "$acrostic"
